name: Processing_DoH_servers_IPs_lists
on:
  schedule:
    - cron: "22 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Use latest node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: node write_file_DoH_IPs.js
      - run: node processed_DoH_servers_IPs.js
      - run: node processed_DoH_servers_IPs_seperated_files.js
      - run: node processed_DoH_servers_IPs_AdGuard.js
      - name: Commit & Push
        uses: actions-x/commit@v6
        with:
          fetch_depth: 0     # fetch full history before committing
          amend: false
          push: true
